from __future__ import annotations

# Product taxonomy: stable codes are stored on user records; labels/icons can evolve.
# Keep codes lowercase, URL/JSON safe, and never use the display label as an identifier.

INDUSTRIES: list[dict[str, str]] = [
    {"code": "technology", "label": "Technology"},
    {"code": "science", "label": "Science & Research"},
    {"code": "engineering", "label": "Engineering"},
    {"code": "healthcare", "label": "Healthcare & Medicine"},
    {"code": "education", "label": "Education"},
    {"code": "finance", "label": "Finance & Banking"},
    {"code": "business", "label": "Business & Consulting"},
    {"code": "legal", "label": "Legal"},
    {"code": "government", "label": "Government & Public Service"},
    {"code": "nonprofit", "label": "Nonprofit & Social Impact"},
    {"code": "media", "label": "Media & Journalism"},
    {"code": "creative", "label": "Creative Arts & Design"},
    {"code": "agriculture", "label": "Agriculture & Agribusiness"},
    {"code": "food", "label": "Food & Beverage"},
    {"code": "manufacturing", "label": "Manufacturing"},
    {"code": "construction", "label": "Construction & Built Environment"},
    {"code": "energy", "label": "Energy & Utilities"},
    {"code": "telecommunications", "label": "Telecommunications"},
    {"code": "transportation", "label": "Transportation & Mobility"},
    {"code": "logistics", "label": "Logistics & Supply Chain"},
    {"code": "automotive", "label": "Automotive"},
    {"code": "aerospace", "label": "Aerospace & Aviation"},
    {"code": "maritime", "label": "Maritime & Shipping"},
    {"code": "mining", "label": "Mining & Natural Resources"},
    {"code": "real_estate", "label": "Real Estate & Property"},
    {"code": "retail", "label": "Retail & Commerce"},
    {"code": "hospitality", "label": "Hospitality & Tourism"},
    {"code": "sports", "label": "Sports & Recreation"},
    {"code": "environment", "label": "Environment & Sustainability"},
    {"code": "security", "label": "Security & Safety"},
    {"code": "professional_services", "label": "Professional Services"},
    {"code": "religion", "label": "Faith & Religious Organizations"},
    {"code": "beauty_wellness", "label": "Beauty & Wellness"},
]

_ROLES: list[tuple[str, str, str]] = [
    # Technology
    ("software_engineer", "Software Engineer", "technology"),
    ("frontend_developer", "Frontend Developer", "technology"),
    ("backend_developer", "Backend Developer", "technology"),
    ("fullstack_developer", "Full-Stack Developer", "technology"),
    ("mobile_developer", "Mobile Developer", "technology"),
    ("web_developer", "Web Developer", "technology"),
    ("devops_engineer", "DevOps Engineer", "technology"),
    ("cloud_engineer", "Cloud Engineer", "technology"),
    ("data_engineer", "Data Engineer", "technology"),
    ("data_scientist", "Data Scientist", "technology"),
    ("ai_ml_engineer", "AI / ML Engineer", "technology"),
    ("cybersecurity_specialist", "Cybersecurity Specialist", "technology"),
    ("network_engineer", "Network Engineer", "technology"),
    ("database_administrator", "Database Administrator", "technology"),
    ("qa_engineer", "QA Engineer", "technology"),
    ("systems_administrator", "Systems Administrator", "technology"),
    ("solutions_architect", "Solutions Architect", "technology"),
    ("product_manager", "Product Manager", "technology"),
    ("ux_designer", "UX Designer", "technology"),
    ("ui_designer", "UI Designer", "technology"),
    ("product_designer", "Product Designer", "technology"),
    ("technical_writer", "Technical Writer", "technology"),
    ("it_consultant", "IT Consultant", "technology"),
    # Science & research
    ("physicist", "Physicist", "science"),
    ("mathematician", "Mathematician", "science"),
    ("statistician", "Statistician", "science"),
    ("chemist", "Chemist", "science"),
    ("biologist", "Biologist", "science"),
    ("microbiologist", "Microbiologist", "science"),
    ("geneticist", "Geneticist", "science"),
    ("biochemist", "Biochemist", "science"),
    ("neuroscientist", "Neuroscientist", "science"),
    ("astronomer", "Astronomer", "science"),
    ("geologist", "Geologist", "science"),
    ("environmental_scientist", "Environmental Scientist", "science"),
    ("research_scientist", "Research Scientist", "science"),
    ("laboratory_scientist", "Laboratory Scientist", "science"),
    # Engineering
    ("civil_engineer", "Civil Engineer", "engineering"),
    ("mechanical_engineer", "Mechanical Engineer", "engineering"),
    ("electrical_engineer", "Electrical Engineer", "engineering"),
    ("electronics_engineer", "Electronics Engineer", "engineering"),
    ("chemical_engineer", "Chemical Engineer", "engineering"),
    ("structural_engineer", "Structural Engineer", "engineering"),
    ("environmental_engineer", "Environmental Engineer", "engineering"),
    ("biomedical_engineer", "Biomedical Engineer", "engineering"),
    ("mechatronics_engineer", "Mechatronics Engineer", "engineering"),
    ("industrial_engineer", "Industrial Engineer", "engineering"),
    ("telecommunications_engineer", "Telecommunications Engineer", "engineering"),
    ("agricultural_engineer", "Agricultural Engineer", "engineering"),
    ("petroleum_engineer", "Petroleum Engineer", "engineering"),
    ("mining_engineer", "Mining Engineer", "engineering"),
    ("aerospace_engineer", "Aerospace Engineer", "engineering"),
    # Healthcare
    ("doctor", "Doctor", "healthcare"),
    ("physician", "Physician", "healthcare"),
    ("surgeon", "Surgeon", "healthcare"),
    ("nurse", "Nurse", "healthcare"),
    ("pharmacist", "Pharmacist", "healthcare"),
    ("dentist", "Dentist", "healthcare"),
    ("clinical_officer", "Clinical Officer", "healthcare"),
    ("physiotherapist", "Physiotherapist", "healthcare"),
    ("radiographer", "Radiographer", "healthcare"),
    ("laboratory_technologist", "Laboratory Technologist", "healthcare"),
    ("nutritionist", "Nutritionist", "healthcare"),
    ("psychologist", "Psychologist", "healthcare"),
    ("occupational_therapist", "Occupational Therapist", "healthcare"),
    ("public_health_specialist", "Public Health Specialist", "healthcare"),
    ("medical_researcher", "Medical Researcher", "healthcare"),
    # Education
    ("teacher", "Teacher", "education"),
    ("lecturer", "Lecturer", "education"),
    ("professor", "Professor", "education"),
    ("tutor", "Tutor", "education"),
    ("academic_researcher", "Academic Researcher", "education"),
    ("education_consultant", "Education Consultant", "education"),
    ("curriculum_developer", "Curriculum Developer", "education"),
    ("school_administrator", "School Administrator", "education"),
    ("education_technologist", "Education Technologist", "education"),
    ("instructional_designer", "Instructional Designer", "education"),
    # Business & finance
    ("entrepreneur", "Entrepreneur", "business"),
    ("founder", "Founder", "business"),
    ("ceo", "CEO", "business"),
    ("business_consultant", "Business Consultant", "business"),
    ("business_analyst", "Business Analyst", "business"),
    ("accountant", "Accountant", "finance"),
    ("auditor", "Auditor", "finance"),
    ("financial_analyst", "Financial Analyst", "finance"),
    ("economist", "Economist", "finance"),
    ("investment_analyst", "Investment Analyst", "finance"),
    ("banker", "Banker", "finance"),
    ("insurance_specialist", "Insurance Specialist", "finance"),
    ("financial_advisor", "Financial Advisor", "finance"),
    ("procurement_specialist", "Procurement Specialist", "business"),
    ("operations_manager", "Operations Manager", "business"),
    # Legal / public service
    ("lawyer", "Lawyer", "legal"),
    ("advocate", "Advocate", "legal"),
    ("legal_consultant", "Legal Consultant", "legal"),
    ("paralegal", "Paralegal", "legal"),
    ("legal_researcher", "Legal Researcher", "legal"),
    ("mediator", "Mediator", "legal"),
    ("compliance_specialist", "Compliance Specialist", "legal"),
    ("public_servant", "Public Servant", "government"),
    ("policy_analyst", "Policy Analyst", "government"),
    ("civil_servant", "Civil Servant", "government"),
    # Media / creative
    ("journalist", "Journalist", "media"),
    ("editor", "Editor", "media"),
    ("writer", "Writer", "creative"),
    ("author", "Author", "creative"),
    ("poet", "Poet", "creative"),
    ("photographer", "Photographer", "creative"),
    ("filmmaker", "Filmmaker", "creative"),
    ("director", "Director", "creative"),
    ("illustrator", "Illustrator", "creative"),
    ("graphic_designer", "Graphic Designer", "creative"),
    ("animator", "Animator", "creative"),
    ("musician", "Musician", "creative"),
    ("music_producer", "Music Producer", "creative"),
    ("actor", "Actor", "creative"),
    ("artist", "Artist", "creative"),
    ("architect", "Architect", "construction"),
    ("fashion_designer", "Fashion Designer", "creative"),
    # Agriculture / food
    ("farmer", "Farmer", "agriculture"),
    ("agronomist", "Agronomist", "agriculture"),
    ("horticulturist", "Horticulturist", "agriculture"),
    ("veterinarian", "Veterinarian", "agriculture"),
    ("animal_scientist", "Animal Scientist", "agriculture"),
    ("agricultural_economist", "Agricultural Economist", "agriculture"),
    ("fisheries_specialist", "Fisheries Specialist", "agriculture"),
    ("food_scientist", "Food Scientist", "food"),
    ("chef", "Chef", "food"),
    ("restaurateur", "Restaurateur", "food"),
    # Built environment / energy / telecom / mobility
    ("construction_manager", "Construction Manager", "construction"),
    ("quantity_surveyor", "Quantity Surveyor", "construction"),
    ("land_surveyor", "Land Surveyor", "construction"),
    ("electrician", "Electrician", "engineering"),
    ("energy_engineer", "Energy Engineer", "energy"),
    ("renewable_energy_specialist", "Renewable Energy Specialist", "energy"),
    ("telecom_specialist", "Telecommunications Specialist", "telecommunications"),
    ("logistics_manager", "Logistics Manager", "logistics"),
    ("supply_chain_specialist", "Supply Chain Specialist", "logistics"),
    ("pilot", "Pilot", "aerospace"),
    ("aviation_specialist", "Aviation Specialist", "aerospace"),
    ("seafarer", "Seafarer", "maritime"),
    ("marine_engineer", "Marine Engineer", "maritime"),
    ("mining_geologist", "Mining Geologist", "mining"),
    ("real_estate_agent", "Real Estate Agent", "real_estate"),
    ("property_manager", "Property Manager", "real_estate"),
    ("retail_manager", "Retail Manager", "retail"),
    ("hotel_manager", "Hotel Manager", "hospitality"),
    ("tourism_professional", "Tourism Professional", "hospitality"),
    # Sport / environment / security / wellness
    ("athlete", "Athlete", "sports"),
    ("coach", "Coach", "sports"),
    ("sports_analyst", "Sports Analyst", "sports"),
    ("environmental_consultant", "Environmental Consultant", "environment"),
    ("sustainability_specialist", "Sustainability Specialist", "environment"),
    ("conservationist", "Conservationist", "environment"),
    ("security_specialist", "Security Specialist", "security"),
    ("safety_officer", "Safety Officer", "security"),
    ("security_analyst", "Security Analyst", "security"),
    ("fitness_trainer", "Fitness Trainer", "beauty_wellness"),
    ("wellness_coach", "Wellness Coach", "beauty_wellness"),
    ("beauty_professional", "Beauty Professional", "beauty_wellness"),
    # Faith / social impact / general professional services
    ("clergy", "Clergy / Religious Leader", "religion"),
    ("faith_worker", "Faith Worker", "religion"),
    ("social_worker", "Social Worker", "nonprofit"),
    ("ngo_professional", "NGO Professional", "nonprofit"),
    ("project_manager", "Project Manager", "professional_services"),
    ("management_consultant", "Management Consultant", "professional_services"),
    (
        "human_resources_specialist",
        "Human Resources Specialist",
        "professional_services",
    ),
    ("recruiter", "Recruiter", "professional_services"),
    ("manufacturing_engineer", "Manufacturing Engineer", "manufacturing"),
    ("production_manager", "Production Manager", "manufacturing"),
    ("quality_manager", "Quality Manager", "manufacturing"),
    ("industrial_designer", "Industrial Designer", "manufacturing"),
    ("automotive_engineer", "Automotive Engineer", "automotive"),
    ("automotive_technician", "Automotive Technician", "automotive"),
    ("mechanic", "Mechanic", "automotive"),
    ("transport_manager", "Transport Manager", "transportation"),
    ("fleet_manager", "Fleet Manager", "transportation"),
    ("dispatcher", "Dispatcher", "transportation"),
    ("warehouse_manager", "Warehouse Manager", "logistics"),
    ("supply_chain_manager", "Supply Chain Manager", "logistics"),
    ("electric_power_specialist", "Electric Power Specialist", "energy"),
    ("utilities_manager", "Utilities Manager", "energy"),
    ("solar_energy_specialist", "Solar Energy Specialist", "energy"),
    ("telecom_engineer", "Telecom Engineer", "telecommunications"),
    ("network_technician", "Network Technician", "telecommunications"),
    ("miner", "Mining Professional", "mining"),
    ("geospatial_specialist", "Geospatial Specialist", "mining"),
    ("real_estate_consultant", "Real Estate Consultant", "real_estate"),
    ("property_developer", "Property Developer", "real_estate"),
    ("merchandiser", "Merchandiser", "retail"),
    ("retail_buyer", "Retail Buyer", "retail"),
    ("event_manager", "Event Manager", "hospitality"),
    ("travel_consultant", "Travel Consultant", "hospitality"),
    ("restaurant_manager", "Restaurant Manager", "food"),
    ("brewer", "Brewer", "food"),
    ("marine_scientist", "Marine Scientist", "maritime"),
    ("naval_architect", "Naval Architect", "maritime"),
    ("aviation_manager", "Aviation Manager", "aerospace"),
    ("air_traffic_specialist", "Air Traffic Specialist", "aerospace"),
    ("athletic_trainer", "Athletic Trainer", "sports"),
    ("sports_manager", "Sports Manager", "sports"),
]

# Compact icon keys consumed by clients. The client remains responsible for mapping
# these keys to its icon library, so backend labels never dictate presentation.
ICON_BY_ROLE: dict[str, str] = {
    "physicist": "atom",
    "mathematician": "function",
    "statistician": "function",
    "chemist": "flask-outline",
    "biologist": "microscope",
    "microbiologist": "microscope",
    "geneticist": "atom",
    "research_scientist": "microscope",
    "laboratory_scientist": "flask-outline",
    "doctor": "medical-bag",
    "physician": "medical-bag",
    "surgeon": "medical-bag",
    "nurse": "medical-bag",
    "pharmacist": "pill",
    "dentist": "tooth-outline",
    "psychologist": "account-heart-outline",
    "civil_engineer": "office-building",
    "mechanical_engineer": "cog-outline",
    "electrical_engineer": "flash-outline",
    "electronics_engineer": "cog-outline",
    "chemical_engineer": "flask-outline",
    "structural_engineer": "office-building",
    "software_engineer": "code-tags",
    "frontend_developer": "code-tags",
    "backend_developer": "server-outline",
    "fullstack_developer": "code-tags",
    "mobile_developer": "cellphone",
    "web_developer": "web",
    "devops_engineer": "infinity",
    "cloud_engineer": "cloud-outline",
    "data_engineer": "database-outline",
    "data_scientist": "chart-line",
    "ai_ml_engineer": "brain",
    "cybersecurity_specialist": "shield-lock-outline",
    "network_engineer": "lan-connect",
    "database_administrator": "database",
    "qa_engineer": "bug-check-outline",
    "teacher": "school-outline",
    "lecturer": "school-outline",
    "professor": "school-outline",
    "tutor": "school-outline",
    "entrepreneur": "lightbulb-outline",
    "founder": "rocket-launch-outline",
    "ceo": "briefcase-outline",
    "accountant": "calculator",
    "auditor": "clipboard-check-outline",
    "financial_analyst": "chart-line",
    "economist": "chart-line",
    "banker": "bank-outline",
    "lawyer": "scale-balance",
    "advocate": "scale-balance",
    "journalist": "newspaper-variant-outline",
    "writer": "pencil-outline",
    "author": "book-open-outline",
    "poet": "format-quote-close",
    "photographer": "camera-outline",
    "filmmaker": "movie-open-outline",
    "graphic_designer": "palette-outline",
    "artist": "palette-outline",
    "architect": "ruler-square",
    "farmer": "sprout-outline",
    "agronomist": "sprout-outline",
    "horticulturist": "flower-outline",
    "veterinarian": "paw-outline",
    "food_scientist": "food-apple-outline",
    "chef": "silverware-fork-knife",
    "pilot": "airplane",
    "aviation_specialist": "airplane",
    "seafarer": "ferry",
    "marine_engineer": "ferry",
    "athlete": "run",
    "coach": "bullhorn-outline",
    "environmental_consultant": "leaf",
    "sustainability_specialist": "leaf",
    "conservationist": "tree-outline",
    "security_specialist": "shield-outline",
    "security_analyst": "shield-outline",
    "safety_officer": "hard-hat",
    "clergy": "church-outline",
    "faith_worker": "church-outline",
    "social_worker": "account-heart-outline",
}

ROLES: list[dict[str, str]] = [
    {
        "code": code,
        "label": label,
        "industry_code": industry,
        "icon": ICON_BY_ROLE.get(code, "briefcase-outline"),
    }
    for code, label, industry in _ROLES
]

INDUSTRY_CODES = {item["code"] for item in INDUSTRIES}
ROLE_MAP = {item["code"]: item for item in ROLES}


def validate_identity_selection(
    industry_codes: list[str], role_codes: list[str], primary_role: str | None
) -> None:
    unknown_industries = sorted(set(industry_codes) - INDUSTRY_CODES)
    unknown_roles = sorted(set(role_codes) - ROLE_MAP.keys())
    if unknown_industries:
        raise ValueError(f"Unknown industries: {', '.join(unknown_industries)}")
    if unknown_roles:
        raise ValueError(f"Unknown professional roles: {', '.join(unknown_roles)}")
    if primary_role is not None and primary_role not in role_codes:
        raise ValueError(
            "Primary professional role must be one of the selected professional roles."
        )
